services:
  # MetaModelsTemplateHelper
  App\Helper\MetaModelsTemplateHelper:
    public: true
    arguments:
      - '@metamodels.factory'
      - '@metamodels.filter_setting_factory'
      - '@metamodels.render_setting_factory'

  # Form data.
  App\EventListener\ProcessFormDataListener:
    public: true
    arguments:
      - '@metamodels.factory'
    tags:
      - { name: contao.hook, hook: processFormData }

  # PrePersistModelEventListener
  App\EventListener\PrePersistModelEventListener:
    public: true
    arguments:
      - '@metamodels.factory'
    tags:
      - { name: kernel.event_listener, event: dc-general.model.pre-persist }

  # GetPropertyOptionsListener
  App\EventListener\GetPropertyOptionsListener:
    public: true
    arguments:
      - '@metamodels.factory'
    tags:
      - { name: kernel.event_listener, event: dc-general.view.contao2backend.get-property-options }

  # Special filter for division
  App\Filter\DivisionFilterFactory:
    arguments:
      - '@translator'
      - '@metamodels.factory'
      - '@Doctrine\DBAL\Connection'
      - '@cca.dc-general.scope-matcher'
      - '@request_stack'
    tags:
      - { name: metamodels.filter_factory }
  App\Filter\DivisionFilterSettingTypeRendererListener:
    arguments:
      - '@metamodels.filter_setting_factory'
      - '@event_dispatcher'
      - '@metamodels.assets.icon_builder'
      - '@cca.dc-general.scope-matcher'
    tags:
      - { name: kernel.event_listener, event: 'dc-general.view.contao2backend.model-to-label', method: modelToLabel }
